// Static market and route data used by the globe, rate checker, and fallback rate display.
(function attachWapiRoutes(global) {
  const MARKET_DEFINITIONS = {
    lagos: {
      id: "lagos",
      label: "Lagos",
      country: "Nigeria",
      lat: 6.5244,
      lng: 3.3792,
    },
    kampala: {
      id: "kampala",
      label: "Kampala",
      country: "Uganda",
      lat: 0.3476,
      lng: 32.5825,
    },
    darEsSalaam: {
      id: "darEsSalaam",
      label: "Dar es Salaam",
      country: "Tanzania",
      lat: -6.7924,
      lng: 39.2083,
    },
    nairobi: {
      id: "nairobi",
      label: "Nairobi",
      country: "Kenya",
      lat: -1.286389,
      lng: 36.817223,
    },
    london: {
      id: "london",
      label: "London",
      country: "United Kingdom",
      lat: 51.5072,
      lng: -0.1276,
    },
    newYork: {
      id: "newYork",
      label: "New York",
      country: "United States",
      lat: 40.7128,
      lng: -74.006,
    },
    mumbai: {
      id: "mumbai",
      label: "Mumbai",
      country: "India",
      lat: 19.076,
      lng: 72.8777,
    },
    guangzhou: {
      id: "guangzhou",
      label: "Guangzhou",
      country: "China",
      lat: 23.1291,
      lng: 113.2644,
    },
  };

  // Route IDs must stay stable because UI selects, analytics, and future live rates depend on them.
  const ROUTE_DEFINITIONS = [
    {
      id: "nairobi-dar-es-salaam",
      title: "Nairobi to Dar es Salaam",
      rateCheckLabel: "Kenya to Tanzania",
      rate: "1 USD = 2589.00 TZS",
      heroRate: "1 KES = 20.16 TZS",
      multiplier: 2589,
      outputCurrency: "TZS",
      rates: {
        USD: { rate: "1 USD = 2,589.00 TZS", multiplier: 2589 },
        KES: { rate: "1 KES = 20.16 TZS", multiplier: 20.16 },
        UGX: { rate: "1 TZS = 1.39 UGX", multiplier: 0.7208 },
      },
      color: "#00b549",
      from: "nairobi",
      to: "darEsSalaam",
      arcAltitude: 0.1,
      animationMs: 2600,
      focus: { lat: -3.8, lng: 38.3, altitude: 1.28 },
    },
    {
      id: "nairobi-kampala",
      title: "Nairobi to Kampala",
      rateCheckLabel: "Kenya to Uganda",
      rate: "1 USD = 3740.00 UGX",
      heroRate: "1 KES = 29.13 UGX",
      multiplier: 3740,
      outputCurrency: "UGX",
      rates: {
        USD: { rate: "1 USD = 3,740.00 UGX", multiplier: 3740 },
        KES: { rate: "1 KES = 29.13 UGX", multiplier: 29.13 },
        UGX: { rate: "1 UGX = 1.00 UGX", multiplier: 1 },
      },
      color: "#00b549",
      from: "nairobi",
      to: "kampala",
      arcAltitude: 0.1,
      animationMs: 2600,
      focus: { lat: -0.4, lng: 34.8, altitude: 1.24 },
    },
    {
      id: "nairobi-mumbai",
      title: "Nairobi to Mumbai",
      rateCheckLabel: "Kenya to India",
      rate: "1 USD = 83.10 INR",
      heroRate: "1 INR = 1.54 KES",
      multiplier: 83.1,
      outputCurrency: "INR",
      rates: {
        USD: { rate: "1 USD = 83.10 INR", multiplier: 83.1 },
        KES: { rate: "1 INR = 1.54 KES", multiplier: 0.65 },
        UGX: { rate: "1 INR = 43.07 UGX", multiplier: 0.0232 },
      },
      color: "#00b549",
      from: "nairobi",
      to: "mumbai",
      arcAltitude: 0.22,
      animationMs: 3300,
      focus: { lat: 10.6, lng: 55.4, altitude: 1.6 },
    },
    {
      id: "nairobi-london",
      title: "Nairobi to London",
      rateCheckLabel: "Kenya to United Kingdom",
      rate: "1 USD = 0.79 GBP",
      heroRate: "1 GBP = 161.29 KES",
      multiplier: 0.79,
      outputCurrency: "GBP",
      rates: {
        USD: { rate: "1 USD = 0.79 GBP", multiplier: 0.79 },
        KES: { rate: "1 GBP = 161.29 KES", multiplier: 0.0062 },
        UGX: { rate: "1 GBP = 4,511.28 UGX", multiplier: 0.0002217 },
      },
      color: "#00b549",
      from: "nairobi",
      to: "london",
      arcAltitude: 0.26,
      animationMs: 3400,
      focus: { lat: 26.8, lng: 18.6, altitude: 1.8 },
    },
    {
      id: "nairobi-new-york",
      title: "Nairobi to New York",
      rateCheckLabel: "Kenya to United States",
      rate: "1 USD = 1.00 USD",
      heroRate: "1 USD = 128.40 KES",
      multiplier: 1,
      outputCurrency: "USD",
      rates: {
        USD: { rate: "1 USD = 1.00 USD", multiplier: 1 },
        KES: { rate: "1 USD = 128.40 KES", multiplier: 0.0078 },
        UGX: { rate: "1 USD = 3,591.35 UGX", multiplier: 0.0002784 },
      },
      color: "#00b549",
      from: "nairobi",
      to: "newYork",
      arcAltitude: 0.31,
      animationMs: 3600,
      focus: { lat: 22.6, lng: -22.4, altitude: 1.95 },
    },
    {
      id: "nairobi-guangzhou",
      title: "Nairobi to Guangzhou",
      rateCheckLabel: "Kenya to China",
      rate: "1 USD = 7.24 CNY",
      heroRate: "1 CNY = 17.86 KES",
      multiplier: 7.24,
      outputCurrency: "CNY",
      rates: {
        USD: { rate: "1 USD = 7.24 CNY", multiplier: 7.24 },
        KES: { rate: "1 CNY = 17.86 KES", multiplier: 0.056 },
        UGX: { rate: "1 CNY = 499.54 UGX", multiplier: 0.002 },
      },
      color: "#00b549",
      from: "nairobi",
      to: "guangzhou",
      arcAltitude: 0.22,
      animationMs: 3300,
      focus: { lat: 12.4, lng: 73.8, altitude: 1.62 },
    },
    {
      id: "kampala-nairobi",
      title: "Kampala to Nairobi",
      rateCheckLabel: "Uganda to Kenya",
      rate: "1 USD = 128.40 KES",
      heroRate: "1 KES = 27.97 UGX",
      multiplier: 128.4,
      outputCurrency: "KES",
      rates: {
        USD: { rate: "1 USD = 128.40 KES", multiplier: 128.4 },
        KES: { rate: "1 KES = 1.00 KES", multiplier: 1 },
        UGX: { rate: "1 KES = 27.97 UGX", multiplier: 0.03575 },
      },
      color: "#045d56",
      from: "kampala",
      to: "nairobi",
      arcAltitude: 0.1,
      animationMs: 2600,
      focus: { lat: -0.4, lng: 34.8, altitude: 1.24 },
    },
    {
      id: "kampala-dar-es-salaam",
      title: "Kampala to Dar es Salaam",
      rateCheckLabel: "Uganda to Tanzania",
      rate: "1 USD = 2589.00 TZS",
      heroRate: "1 TZS = 1.39 UGX",
      multiplier: 2589,
      outputCurrency: "TZS",
      rates: {
        USD: { rate: "1 USD = 2,589.00 TZS", multiplier: 2589 },
        KES: { rate: "1 KES = 20.16 TZS", multiplier: 20.16 },
        UGX: { rate: "1 TZS = 1.39 UGX", multiplier: 0.7208 },
      },
      color: "#045d56",
      from: "kampala",
      to: "darEsSalaam",
      arcAltitude: 0.1,
      animationMs: 2600,
      focus: { lat: -3.6, lng: 37.2, altitude: 1.3 },
    },
    {
      id: "kampala-mumbai",
      title: "Kampala to Mumbai",
      rateCheckLabel: "Uganda to India",
      rate: "1 USD = 83.10 INR",
      heroRate: "1 INR = 43.07 UGX",
      multiplier: 83.1,
      outputCurrency: "INR",
      rates: {
        USD: { rate: "1 USD = 83.10 INR", multiplier: 83.1 },
        KES: { rate: "1 INR = 1.54 KES", multiplier: 0.65 },
        UGX: { rate: "1 INR = 43.07 UGX", multiplier: 0.0232 },
      },
      color: "#045d56",
      from: "kampala",
      to: "mumbai",
      arcAltitude: 0.22,
      animationMs: 3300,
      focus: { lat: 10.6, lng: 55.4, altitude: 1.6 },
    },
    {
      id: "kampala-guangzhou",
      title: "Kampala to Guangzhou",
      rateCheckLabel: "Uganda to China",
      rate: "1 USD = 7.24 CNY",
      heroRate: "1 CNY = 499.54 UGX",
      multiplier: 7.24,
      outputCurrency: "CNY",
      rates: {
        USD: { rate: "1 USD = 7.24 CNY", multiplier: 7.24 },
        KES: { rate: "1 CNY = 17.86 KES", multiplier: 0.056 },
        UGX: { rate: "1 CNY = 499.54 UGX", multiplier: 0.002 },
      },
      color: "#045d56",
      from: "kampala",
      to: "guangzhou",
      arcAltitude: 0.22,
      animationMs: 3300,
      focus: { lat: 12.4, lng: 73.8, altitude: 1.62 },
    },
    {
      id: "kampala-london",
      title: "Kampala to London",
      rateCheckLabel: "Uganda to United Kingdom",
      rate: "1 USD = 0.79 GBP",
      heroRate: "1 GBP = 4,511.28 UGX",
      multiplier: 0.79,
      outputCurrency: "GBP",
      rates: {
        USD: { rate: "1 USD = 0.79 GBP", multiplier: 0.79 },
        KES: { rate: "1 GBP = 161.29 KES", multiplier: 0.0062 },
        UGX: { rate: "1 GBP = 4,511.28 UGX", multiplier: 0.0002217 },
      },
      color: "#045d56",
      from: "kampala",
      to: "london",
      arcAltitude: 0.26,
      animationMs: 3400,
      focus: { lat: 26.8, lng: 18.6, altitude: 1.8 },
    },
    {
      id: "kampala-new-york",
      title: "Kampala to New York",
      rateCheckLabel: "Uganda to United States",
      rate: "1 USD = 1.00 USD",
      heroRate: "1 USD = 3,591.35 UGX",
      multiplier: 1,
      outputCurrency: "USD",
      rates: {
        USD: { rate: "1 USD = 1.00 USD", multiplier: 1 },
        KES: { rate: "1 USD = 128.40 KES", multiplier: 0.0078 },
        UGX: { rate: "1 USD = 3,591.35 UGX", multiplier: 0.0002784 },
      },
      color: "#045d56",
      from: "kampala",
      to: "newYork",
      arcAltitude: 0.31,
      animationMs: 3600,
      focus: { lat: 22.6, lng: -22.4, altitude: 1.95 },
    },
    {
      id: "nairobi-lagos",
      title: "Nairobi to Lagos",
      rateCheckLabel: "Kenya to Nigeria",
      rate: "1 USD = 1548.20 NGN",
      heroRate: "1 KES = 12.06 NGN",
      multiplier: 1548.2,
      outputCurrency: "NGN",
      rates: {
        USD: { rate: "1 USD = 1,548.20 NGN", multiplier: 1548.2 },
        KES: { rate: "1 KES = 12.06 NGN", multiplier: 12.06 },
        UGX: { rate: "1 NGN = 2.32 UGX", multiplier: 0.4312 },
      },
      color: "#00b549",
      from: "nairobi",
      to: "lagos",
      arcAltitude: 0.18,
      animationMs: 3000,
      focus: { lat: 4.4, lng: 19.8, altitude: 1.56 },
    },
  ];

  const DEFAULT_ROUTE_ID = "nairobi-mumbai";
  const DEFAULT_BASE_CURRENCY = "USD";
  const BASE_CURRENCY_OPTIONS = [
    { code: "USD", label: "USD" },
    { code: "KES", label: "KES" },
    { code: "UGX", label: "UGX" },
  ];

  // Mutable rate store: static defaults live here, and live rates can hydrate this map later.
  const sharedRouteRates = new Map(
    ROUTE_DEFINITIONS.map(({ id, rate, multiplier, outputCurrency, rateCheckLabel, rates }) => [
      id,
      {
        label: rateCheckLabel,
        outputCurrency,
        rates: rates || {
          USD: { rate, multiplier },
        },
      },
    ])
  );

  const formatRateAmount = (value) =>
    new Intl.NumberFormat("en-US", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(value);

  global.WapiRoutes = {
    DEFAULT_ROUTE_ID,
    DEFAULT_BASE_CURRENCY,
    BASE_CURRENCY_OPTIONS,
    MARKET_DEFINITIONS,
    ROUTE_DEFINITIONS,
    sharedRouteRates,
    formatRateAmount,
  };
})(window);
